### PR TITLE
🎨  feat: Add Background

### PR DESCRIPTION
**Pull request by RaxCruz**
## Description

[5930](https://redmine.kingkit.codes/issues/5930)

## Motivation and Context

切版- 背景

## Screenshots (if appropriate)

截圖 2022-10-19 下午2 17 28

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by shengyuan — COMMENTED** [review]
不太理解，這裡的修改並沒有引入 `index.css` 是如何生效？

**Comment by shengyuan** [comment]
> 不太理解，這裡的修改並沒有引入 `index.css` 是如何生效？

直覺會是修改 `app.css` 才對，但實際上並不是，讓人覺得疑惑 🤔

**Comment by RaxCruz** [comment]
這邊的 index.css 是從 index.tsx 引入的， 如下圖
截圖 2022-10-20 上午11 50 30

**Comment by shengyuan** [comment]
發生衝突了，請再處理一下。

**Pull request closed without merging**
